version: 2
refs:
  container: &container
    docker:
      - image: node:8.16
    working_directory: ~/repo
  steps:
    - &Versions
      run:
        name: Versions
        command: node -v && npm -v && yarn -v
    - &Install
      run:
        name: Install Dependencies
        command: yarn install --pure-lockfile
    - &Build
      run:
        name: Build
        command: yarn build
    - &Lint
      run:
        name: Lint
        command: yarn lint
    - &Test
      run:
        name: Test
        command: yarn test --coverage && yarn codecov

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Build
      - *Test
      - *Lint

  next:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Build
      - *Test
      - *Lint

  master:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Build
      - *Test
      - *Lint

workflows:
  version: 2
  all:
    jobs:
      - all:
          context: global-env-vars
          filters:
            branches:
              ignore:
                - master
                - next
  next:
    jobs:
      - next:
          context: global-env-vars
          filters:
            branches:
              only: next
  master:
    jobs:
      - master:
          context: global-env-vars
          filters:
            branches:
              only: master
